#!/bin/bash
echo setup system proxy...
export ALL_PROXY="socks://${socks_proxy_host:=127.0.0.1}:${socks_proxy_port:=1081}/"
export FTP_PROXY="http://${http_proxy_host:=127.0.0.1}:${http_proxy_port:=1082}/"
export HTTPS_PROXY="http://${http_proxy_host:=127.0.0.1}:${http_proxy_port:=1082}/"
export HTTP_PROXY="http://${http_proxy_host:=127.0.0.1}:${http_proxy_port:=1082}/"
export all_proxy="socks://${socks_proxy_host:=127.0.0.1}:${socks_proxy_port:=1081}/"
export ftp_proxy="http://${http_proxy_host:=127.0.0.1}:${http_proxy_port:=1082}/"
export http_proxy="http://${http_proxy_host:=127.0.0.1}:${http_proxy_port:=1082}/"
export https_proxy="http://${http_proxy_host:=127.0.0.1}:${http_proxy_port:=1082}/"

dconf write /system/proxy/http/host "'$http_proxy_host'"
dconf write /system/proxy/http/port "$http_proxy_port"
dconf write /system/proxy/https/host "'$http_proxy_host'"
dconf write /system/proxy/https/port "$http_proxy_port"
dconf write /system/proxy/ftp/host "'$http_proxy_host'"
dconf write /system/proxy/ftp/port "$http_proxy_port"
dconf write /system/proxy/socks/host "'$socks_proxy_host'"
dconf write /system/proxy/socks/port "$socks_proxy_port"
dconf write /system/proxy/mode "'manual'"
